---
resources:
- name: repo
  type: git
  source:
    uri: https://github.com/dolph/docker-image-ubuntu-rust
- name: daily
  type: time
  source:
    interval: 24h
- name: image
  type: docker-image
  source:
    repository: dolphm/ubuntu-latest-rust-nightly
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}

jobs:
- name: build-image
  serial: true
  build_logs_to_retain: 3
  plan:
  - get: repo
    trigger: true
  - get: daily
    trigger: true
  - put: image
    attempts: 20
    params:
      build: repo/docker
